DROP TABLE IF EXISTS SINGER_TRACK CASCADE;
DROP TABLE IF EXISTS AUTHOR_SONG CASCADE;
DROP TABLE IF EXISTS ALBUM_CONTENT CASCADE;
DROP TABLE IF EXISTS ALBUM CASCADE;
DROP TABLE IF EXISTS TRACK CASCADE;
